steps:

  # Build Container 1 image
  #REFERENCE: https://cloud.google.com/artifact-registry/docs/integrate-gke
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/k8-assignment-app/container1/cnt1', './']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/k8-assignment-app/container1/cnt1']
  
  # Deploy Container 1 to GKE
  # REFERENCE: https://cloud.google.com/build/docs/deploying-builds/deploy-gke
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=./K8_manifests/
      - --image=us-central1-docker.pkg.dev/k8-assignment-app/container1/cnt1
      - --location=us-central1-a
      - --cluster=emayan-assignment-cluster
