apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-for-k8-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
#REFERENCE: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
